apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:simonjamesrowe/jx3-pipeline-catalog/tasks/gradle/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 1Gi
          workingDir: /workspace/source
        steps:
        - image: uses:simonjamesrowe/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: build-gradle-build
          resources: {}
          script: |
            #!/bin/sh
            source .jx/variables.sh
            cp /.gradle/gradle.properties gradle.properties
                        gradle -I /.gradle/init.gradle build sonarqube publish -Pversion=$VERSION --info
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
